### Import packages
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as T
import torchvision.models as models
import sys
import pandas as pd

In [2]:
!pip install torchnet

     |████████████████████████████████| 686kB 6.9MB/s 
     |████████████████████████████████| 204kB 23.5MB/s 
  Created wheel for torchnet: filename=torchnet-0.0.4-cp36-none-any.whl size=29744 sha256=ec23790c1edfc03a88f25783590ce4da5c3dfe79aab392ec69ba9f9d404d1b3b
  Stored in directory: /root/.cache/pip/wheels/e1/03/fb/1c212c2f20905cdf97fe39022946cf16b8e66ed754a6663400
  Created wheel for visdom: filename=visdom-0.1.8.9-cp36-none-any.whl size=655250 sha256=918f36dc48a176d84723c82852c6751158463fe4268cf060115bd8d9b6d58bc8
  Stored in directory: /root/.cache/pip/wheels/70/19/a7/6d589ed967f4dfefd33bc166d081257bd4ed0cb618dccfd62a
  Created wheel for torchfile: filename=torchfile-0.1.0-cp36-none-any.whl size=5712 sha256=bf5f6015ad7131cda4a0146dce9d70197854d56f171f54805cb3bbd314c1d33e
  Stored in directory: /root/.cache/pip/wheels/b1/c3/d6/9a1cc8f3a99a0fc1124cae20153f36af59a6e683daca0a0814
Successfully built torchnet visdom torchfile


In [3]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

In [ ]:
#!git clone https://github.com/pengshiqi/MURA.git
# import shutil
# shutil.move('/content/MURA', '/content/drive/My Drive/대학원/과제/MURA')

In [ ]:
sys.path.append("/content/drive/My Drive/대학원/과제/MURA")
sys.path.append("/content/drive/My Drive/대학원/과제")

In [ ]:
from config import opt
from main import train
from main import test

/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:125: UserWarning: 
Tesla T4 with CUDA capability sm_75 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the Tesla T4 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))


## 테스트 이미지 패스

In [ ]:
opt.model = 'DenseNet169'
opt.use_visdom = False
opt.print_freq = 1
opt.data_root = '/content/drive/My Drive/대학원/과제/'
opt.train_image_paths = '/content/drive/My Drive/대학원/과제/MURA_DATA/train_image_paths.csv'
opt.test_image_paths = '/content/drive/My Drive/대학원/과제/MURA_DATA/valid_image_paths.csv'
opt.output_csv_path = '/content/drive/My Drive/대학원/과제/output'

In [ ]:
pd.read_csv(opt.train_image_paths).head()

MURA_DATA/train/XR_ELBOW/patient04903/study1_positive/image1.png
0  MURA_DATA/train/XR_ELBOW/patient04904/study1_p...              
1  MURA_DATA/train/XR_ELBOW/patient04904/study1_p...              
2  MURA_DATA/train/XR_ELBOW/patient04905/study1_p...              
3  MURA_DATA/train/XR_ELBOW/patient04905/study1_p...              
4  MURA_DATA/train/XR_ELBOW/patient04906/study1_p...

CSV 에서 ELBOW 제외하고는 제거(드라이브 용량 없음)

In [ ]:

def modify_csv(path) :
    df = pd.read_csv(path, header=None)
    df = df[df[0].str.contains("XR_ELBOW")].reset_index(drop=True)
    df = df[0].str.replace(pat='MURA-v1.1', repl='MURA_DATA', regex=False)
    df.to_csv(path, index=False, header=False)

print("1")
path = '/content/drive/My Drive/대학원/과제/MURA_DATA/valid_image_paths.csv'
modify_csv(path)
print("2")
path = '/content/drive/My Drive/대학원/과제/MURA_DATA/valid_labeled_studies.csv'
modify_csv(path)
print("3")
path = '/content/drive/My Drive/대학원/과제/MURA_DATA/train_labeled_studies.csv'
modify_csv(path)
print("4")
path = '/content/drive/My Drive/대학원/과제/MURA_DATA/train_image_paths.csv'
modify_csv(path)

1
2
3
4


In [ ]:
pd.read_csv(opt.train_image_paths).head()

MURA_DATA/train/XR_ELBOW/patient04903/study1_positive/image1.png
0  MURA_DATA/train/XR_ELBOW/patient04904/study1_p...              
1  MURA_DATA/train/XR_ELBOW/patient04904/study1_p...              
2  MURA_DATA/train/XR_ELBOW/patient04905/study1_p...              
3  MURA_DATA/train/XR_ELBOW/patient04905/study1_p...              
4  MURA_DATA/train/XR_ELBOW/patient04906/study1_p...

In [ ]:
path = '/content/drive/My Drive/대학원/과제/MURA_DATA/valid/XR_ELBOW/patient11659/study1_positive/image1.png'
with open(path, mode='r') as pred_file:
    print(pred_file)

<_io.TextIOWrapper name='/content/drive/My Drive/대학원/과제/MURA_DATA/valid/XR_ELBOW/patient11659/study1_positive/image1.png' mode='r' encoding='UTF-8'>


In [ ]:
train()

User config: 
use_visdom False
env MURA
model DenseNet169
ensemble_model_types ['DenseNet169', 'ResNet152']
ensemble_model_paths ['checkpoints/best_densenet169_0702.pth', 'checkpoints/best_resnet152_0708.pth']
data_root /content/drive/My Drive/대학원/과제/
train_image_paths /content/drive/My Drive/대학원/과제/MURA_DATA/train_image_paths.csv
test_image_paths /content/drive/My Drive/대학원/과제/MURA_DATA/valid_image_paths.csv
output_csv_path /content/drive/My Drive/대학원/과제/output
load_model_path None
batch_size 8
use_gpu True
num_workers 4
print_freq 1
debug_file tmp/debug
result_file result.csv
max_epoch 20
lr 0.0001
lr_decay 0.5
weight_decay 1e-05
parse <bound method Config.parse of <config.config.Config object at 0x7f1c58608048>>
CUDA MODEL!
Training images: 4931 Validation images: 465


0it [00:00, ?it/s]/content/drive/My Drive/대학원/과제/MURA/main.py:102: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  confusion_matrix.add(s(Variable(score.data)).data, target.data)
617it [02:41,  3.81it/s]
0it [00:00, ?it/s]/content/drive/My Drive/대학원/과제/MURA/main.py:162: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  val_input = Variable(input, volatile=True)
/content/drive/My Drive/대학원/과제/MURA/main.py:174: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  print(s(score.data.squeeze()))
/content/drive/My Drive/대학원/과제/MURA/main.py:178: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  confusion_matrix.add(s(score.data.squeeze()), label.type(t.LongTensor))
1it [00:00,  2.78it/s]

tensor([[0.2399, 0.7601],
        [0.1316, 0.8684],
        [0.1787, 0.8213],
        [0.0667, 0.9333],
        [0.1580, 0.8420],
        [0.0801, 0.9199],
        [0.4472, 0.5528],
        [0.0365, 0.9635]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


2it [00:00,  3.13it/s]

tensor([[0.7909, 0.2091],
        [0.7343, 0.2657],
        [0.7427, 0.2573],
        [0.8064, 0.1936],
        [0.4478, 0.5522],
        [0.8806, 0.1194],
        [0.4999, 0.5001],
        [0.6220, 0.3780]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.1313, 0.8687],
        [0.3219, 0.6781],
        [0.4162, 0.5838],
        [0.1124, 0.8876],
        [0.5545, 0.4455],
        [0.8669, 0.1331],
        [0.4886, 0.5114],
        [0.5038, 0.4962]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


6it [00:00,  4.97it/s]

tensor([[0.8527, 0.1473],
        [0.1794, 0.8206],
        [0.5366, 0.4634],
        [0.8931, 0.1069],
        [0.8470, 0.1530],
        [0.5376, 0.4624],
        [0.7741, 0.2259],
        [0.6301, 0.3699]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0983, 0.9017],
        [0.1997, 0.8003],
        [0.1388, 0.8612],
        [0.0805, 0.9195],
        [0.1004, 0.8996],
        [0.7854, 0.2146],
        [0.7386, 0.2614],
        [0.8377, 0.1623]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.8124, 0.1876],
        [0.8160, 0.1840],
        [0.9075, 0.0925],
        [0.8056, 0.1944],
        [0.6267, 0.3733],
        [0.8170, 0.1830],
        [0.1461, 0.8539],
        [0.2523, 0.7477]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


8it [00:01,  6.13it/s]

tensor([[0.6437, 0.3563],
        [0.0978, 0.9022],
        [0.1455, 0.8545],
        [0.1478, 0.8522],
        [0.1555, 0.8445],
        [0.1302, 0.8698],
        [0.7336, 0.2664],
        [0.7728, 0.2272]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.4456, 0.5544],
        [0.6397, 0.3603],
        [0.6043, 0.3957],
        [0.6414, 0.3586],
        [0.8369, 0.1631],
        [0.6698, 0.3302],
        [0.9240, 0.0760],
        [0.4429, 0.5571]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.2691, 0.7309],
        [0.4487, 0.5513],
        [0.6173, 0.3827],
        [0.4505, 0.5495],
        [0.7760, 0.2240],
        [0.3675, 0.6325],
        [0.5824, 0.4176],
        [0.3964, 0.6036]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


12it [00:01,  8.13it/s]

tensor([[0.5536, 0.4464],
        [0.5870, 0.4130],
        [0.4421, 0.5579],
        [0.5911, 0.4089],
        [0.4074, 0.5926],
        [0.4829, 0.5171],
        [0.6709, 0.3291],
        [0.5918, 0.4082]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0691, 0.9309],
        [0.1389, 0.8611],
        [0.8084, 0.1916],
        [0.7317, 0.2683],
        [0.7315, 0.2685],
        [0.0686, 0.9314],
        [0.6180, 0.3820],
        [0.0934, 0.9066]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0870, 0.9130],
        [0.5165, 0.4835],
        [0.4055, 0.5945],
        [0.3023, 0.6977],
        [0.1400, 0.8600],
        [0.4543, 0.5457],
        [0.0512, 0.9488],
        [0.0393, 0.9607]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


14it [00:01,  9.10it/s]

tensor([[0.0256, 0.9744],
        [0.6943, 0.3057],
        [0.8424, 0.1576],
        [0.7378, 0.2622],
        [0.7369, 0.2631],
        [0.8632, 0.1368],
        [0.5450, 0.4550],
        [0.1789, 0.8211]], device='cuda:0')
tensor([1, 0, 0, 0, 1, 1, 1, 1])
tensor([[0.6488, 0.3512],
        [0.8813, 0.1187],
        [0.6197, 0.3803],
        [0.8570, 0.1430],
        [0.5889, 0.4111],
        [0.7298, 0.2702],
        [0.6558, 0.3442],
        [0.4987, 0.5013]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.8018, 0.1982],
        [0.4441, 0.5559],
        [0.6029, 0.3971],
        [0.2374, 0.7626],
        [0.0478, 0.9522],
        [0.6210, 0.3790],
        [0.5108, 0.4892],
        [0.1999, 0.8001]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


18it [00:01, 10.55it/s]

tensor([[0.5198, 0.4802],
        [0.5441, 0.4559],
        [0.3952, 0.6048],
        [0.6297, 0.3703],
        [0.6219, 0.3781],
        [0.7129, 0.2871],
        [0.8517, 0.1483],
        [0.8300, 0.1700]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.7220, 0.2780],
        [0.8348, 0.1652],
        [0.8731, 0.1269],
        [0.8702, 0.1298],
        [0.6057, 0.3943],
        [0.0390, 0.9610],
        [0.0969, 0.9031],
        [0.2413, 0.7587]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0590, 0.9410],
        [0.0947, 0.9053],
        [0.4345, 0.5655],
        [0.2877, 0.7123],
        [0.6769, 0.3231],
        [0.7828, 0.2172],
        [0.7193, 0.2807],
        [0.8810, 0.1190]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


20it [00:02, 11.11it/s]

tensor([[0.7689, 0.2311],
        [0.8302, 0.1698],
        [0.8464, 0.1536],
        [0.1681, 0.8319],
        [0.1639, 0.8361],
        [0.1609, 0.8391],
        [0.6636, 0.3364],
        [0.5496, 0.4504]], device='cuda:0')
tensor([1, 0, 0, 1, 1, 1, 1, 1])
tensor([[0.0738, 0.9262],
        [0.5953, 0.4047],
        [0.0970, 0.9030],
        [0.0583, 0.9417],
        [0.8969, 0.1031],
        [0.8458, 0.1542],
        [0.1729, 0.8271],
        [0.0599, 0.9401]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0463, 0.9537],
        [0.2453, 0.7547],
        [0.0187, 0.9813],
        [0.8606, 0.1394],
        [0.5304, 0.4696],
        [0.6499, 0.3501],
        [0.7534, 0.2466],
        [0.2390, 0.7610]], device='cuda:0')
tensor([1, 1, 1, 0, 1, 1, 1, 1])


24it [00:02, 11.96it/s]

tensor([[0.1574, 0.8426],
        [0.1542, 0.8458],
        [0.8304, 0.1696],
        [0.5861, 0.4139],
        [0.7415, 0.2585],
        [0.6638, 0.3362],
        [0.5972, 0.4028],
        [0.6659, 0.3341]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.8162, 0.1838],
        [0.7693, 0.2307],
        [0.5738, 0.4262],
        [0.0837, 0.9163],
        [0.2163, 0.7837],
        [0.6158, 0.3842],
        [0.6587, 0.3413],
        [0.6602, 0.3398]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.5944, 0.4056],
        [0.6241, 0.3759],
        [0.5030, 0.4970],
        [0.5803, 0.4197],
        [0.3697, 0.6303],
        [0.3095, 0.6905],
        [0.1520, 0.8480],
        [0.1738, 0.8262]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


26it [00:02, 11.50it/s]

tensor([[0.5476, 0.4524],
        [0.6283, 0.3717],
        [0.8081, 0.1919],
        [0.4770, 0.5230],
        [0.6816, 0.3184],
        [0.7848, 0.2152],
        [0.6500, 0.3500],
        [0.7635, 0.2365]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.7185, 0.2815],
        [0.6065, 0.3935],
        [0.5872, 0.4128],
        [0.6368, 0.3632],
        [0.5291, 0.4709],
        [0.8684, 0.1316],
        [0.6282, 0.3718],
        [0.8112, 0.1888]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.5598, 0.4402],
        [0.3929, 0.6071],
        [0.6785, 0.3215],
        [0.2999, 0.7001],
        [0.4267, 0.5733],
        [0.1713, 0.8287],
        [0.7425, 0.2575],
        [0.3918, 0.6082]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])

28it [00:02, 11.71it/s]


tensor([[0.2690, 0.7310],
        [0.3129, 0.6871],
        [0.1724, 0.8276],
        [0.2518, 0.7482],
        [0.0288, 0.9712],
        [0.2760, 0.7240],
        [0.3916, 0.6084],
        [0.3532, 0.6468]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.2849, 0.7151],
        [0.6472, 0.3528],
        [0.6367, 0.3633],
        [0.6666, 0.3334],
        [0.7325, 0.2675],
        [0.4376, 0.5624],
        [0.5333, 0.4667],
        [0.8954, 0.1046]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


32it [00:03, 11.69it/s]

tensor([[0.9065, 0.0935],
        [0.8665, 0.1335],
        [0.6939, 0.3061],
        [0.7148, 0.2852],
        [0.8754, 0.1246],
        [0.8556, 0.1444],
        [0.6652, 0.3348],
        [0.6649, 0.3351]], device='cuda:0')
tensor([1, 1, 1, 1, 0, 0, 0, 0])
tensor([[0.8945, 0.1055],
        [0.8681, 0.1319],
        [0.8994, 0.1006],
        [0.8603, 0.1397],
        [0.8807, 0.1193],
        [0.7472, 0.2528],
        [0.9000, 0.1000],
        [0.7299, 0.2701]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8433, 0.1567],
        [0.7947, 0.2053],
        [0.9048, 0.0952],
        [0.8474, 0.1526],
        [0.8217, 0.1783],
        [0.8987, 0.1013],
        [0.8524, 0.1476],
        [0.8744, 0.1256]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


34it [00:03, 12.01it/s]

tensor([[0.8979, 0.1021],
        [0.8617, 0.1383],
        [0.9213, 0.0787],
        [0.7864, 0.2136],
        [0.8166, 0.1834],
        [0.8392, 0.1608],
        [0.8679, 0.1321],
        [0.8498, 0.1502]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8784, 0.1216],
        [0.8909, 0.1091],
        [0.8834, 0.1166],
        [0.8757, 0.1243],
        [0.6730, 0.3270],
        [0.8161, 0.1839],
        [0.9016, 0.0984],
        [0.8687, 0.1313]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


36it [00:03, 11.37it/s]

tensor([[0.8541, 0.1459],
        [0.8939, 0.1061],
        [0.7776, 0.2224],
        [0.8472, 0.1528],
        [0.9183, 0.0817],
        [0.8487, 0.1513],
        [0.7998, 0.2002],
        [0.8327, 0.1673]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8363, 0.1637],
        [0.7301, 0.2699],
        [0.8119, 0.1881],
        [0.8766, 0.1234],
        [0.9050, 0.0950],
        [0.8897, 0.1103],
        [0.8042, 0.1958],
        [0.7772, 0.2228]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6274, 0.3726],
        [0.9041, 0.0959],
        [0.6313, 0.3687],
        [0.7835, 0.2165],
        [0.8824, 0.1176],
        [0.8531, 0.1469],
        [0.8662, 0.1338],
        [0.8739, 0.1261]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


40it [00:03, 11.75it/s]

tensor([[0.8816, 0.1184],
        [0.5863, 0.4137],
        [0.9069, 0.0931],
        [0.9024, 0.0976],
        [0.8506, 0.1494],
        [0.8369, 0.1631],
        [0.1959, 0.8041],
        [0.3813, 0.6187]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6305, 0.3695],
        [0.8181, 0.1819],
        [0.6173, 0.3827],
        [0.8270, 0.1730],
        [0.8447, 0.1553],
        [0.8886, 0.1114],
        [0.7809, 0.2191],
        [0.7701, 0.2299]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8400, 0.1600],
        [0.3039, 0.6961],
        [0.4073, 0.5927],
        [0.8682, 0.1318],
        [0.7896, 0.2104],
        [0.7957, 0.2043],
        [0.9450, 0.0550],
        [0.7826, 0.2174]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


42it [00:03, 11.79it/s]

tensor([[0.9357, 0.0643],
        [0.9035, 0.0965],
        [0.8400, 0.1600],
        [0.9026, 0.0974],
        [0.8294, 0.1706],
        [0.9243, 0.0757],
        [0.8786, 0.1214],
        [0.8581, 0.1419]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8301, 0.1699],
        [0.8629, 0.1371],
        [0.8586, 0.1414],
        [0.7918, 0.2082],
        [0.7658, 0.2342],
        [0.6971, 0.3029],
        [0.8043, 0.1957],
        [0.8982, 0.1018]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6395, 0.3605],
        [0.6223, 0.3777],
        [0.8845, 0.1155],
        [0.7172, 0.2828],
        [0.8870, 0.1130],
        [0.5900, 0.4100],
        [0.8866, 0.1134],
        [0.7863, 0.2137]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


46it [00:04, 12.51it/s]

tensor([[0.8053, 0.1947],
        [0.8284, 0.1716],
        [0.8905, 0.1095],
        [0.8283, 0.1717],
        [0.8617, 0.1383],
        [0.8735, 0.1265],
        [0.8692, 0.1308],
        [0.8669, 0.1331]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8905, 0.1095],
        [0.8480, 0.1520],
        [0.8734, 0.1266],
        [0.7482, 0.2518],
        [0.8461, 0.1539],
        [0.7976, 0.2024],
        [0.5786, 0.4214],
        [0.7170, 0.2830]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9080, 0.0920],
        [0.8885, 0.1115],
        [0.6546, 0.3454],
        [0.8505, 0.1495],
        [0.6968, 0.3032],
        [0.6791, 0.3209],
        [0.8660, 0.1340],
        [0.6524, 0.3476]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


48it [00:04, 11.92it/s]

tensor([[0.6556, 0.3444],
        [0.7117, 0.2883],
        [0.6411, 0.3589],
        [0.6519, 0.3481],
        [0.8168, 0.1832],
        [0.8738, 0.1262],
        [0.8816, 0.1184],
        [0.8713, 0.1287]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6757, 0.3243],
        [0.6997, 0.3003],
        [0.6201, 0.3799],
        [0.8292, 0.1708],
        [0.8450, 0.1550],
        [0.8712, 0.1288],
        [0.7971, 0.2029],
        [0.6051, 0.3949]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8156, 0.1844],
        [0.8451, 0.1549],
        [0.8930, 0.1070],
        [0.7085, 0.2915],
        [0.6284, 0.3716],
        [0.7316, 0.2684],
        [0.8093, 0.1907],
        [0.8419, 0.1581]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


52it [00:04, 12.20it/s]

tensor([[0.8462, 0.1538],
        [0.8436, 0.1564],
        [0.8647, 0.1353],
        [0.8868, 0.1132],
        [0.8612, 0.1388],
        [0.8752, 0.1248],
        [0.8722, 0.1278],
        [0.8349, 0.1651]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7856, 0.2144],
        [0.7537, 0.2463],
        [0.6679, 0.3321],
        [0.5678, 0.4322],
        [0.5963, 0.4037],
        [0.8211, 0.1789],
        [0.8528, 0.1472],
        [0.6085, 0.3915]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6937, 0.3063],
        [0.5852, 0.4148],
        [0.8924, 0.1076],
        [0.8585, 0.1415],
        [0.7823, 0.2177],
        [0.8650, 0.1350],
        [0.8429, 0.1571],
        [0.5681, 0.4319]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


54it [00:04, 12.79it/s]

tensor([[0.6976, 0.3024],
        [0.8137, 0.1863],
        [0.7138, 0.2862],
        [0.8624, 0.1376],
        [0.8948, 0.1052],
        [0.8865, 0.1135],
        [0.8466, 0.1534],
        [0.8666, 0.1334]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8825, 0.1175],
        [0.8607, 0.1393],
        [0.8549, 0.1451],
        [0.9057, 0.0943],
        [0.8189, 0.1811],
        [0.7869, 0.2131],
        [0.8556, 0.1444],
        [0.8236, 0.1764]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8736, 0.1264],
        [0.5432, 0.4568],
        [0.8465, 0.1535],
        [0.5723, 0.4277],
        [0.7130, 0.2870],
        [0.7560, 0.2440],
        [0.9026, 0.0974],
        [0.7182, 0.2818]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


58it [00:05, 13.51it/s]

tensor([[0.7734, 0.2266],
        [0.8312, 0.1688],
        [0.8310, 0.1690],
        [0.8014, 0.1986],
        [0.8003, 0.1997],
        [0.6229, 0.3771],
        [0.8530, 0.1470],
        [0.8223, 0.1777]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8880, 0.1120],
        [0.8275, 0.1725],
        [0.8692, 0.1308],
        [0.6757, 0.3243],
        [0.7981, 0.2019],
        [0.6745, 0.3255],
        [0.6338, 0.3662],
        [0.8743, 0.1257]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8940, 0.1060],
        [0.8378, 0.1622],
        [0.8790, 0.1210],
        [0.8995, 0.1005],
        [0.8873, 0.1127],
        [0.9112, 0.0888],
        [0.8244, 0.1756],
        [0.8809, 0.1191]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([0.8654, 0.1346], device='cuda:0')
tensor([0])
Error : number of targets and predicted outputs do not match


59it [00:05, 11.12it/s]

val_accuracy:  71.12068965517241
epoch:0,lr:0.0001,loss:0.5016074776649475,train_cm:[[2685  240]
 [ 977 1029]],val_cm:[[230   4]
 [130 100]],train_acc:75.31940782802677, val_acc:71.12068965517241



617it [02:43,  3.77it/s]
2it [00:00,  3.01it/s]

tensor([[0.0387, 0.9613],
        [0.0100, 0.9900],
        [0.0183, 0.9817],
        [0.0057, 0.9943],
        [0.0101, 0.9899],
        [0.0025, 0.9975],
        [0.1214, 0.8786],
        [0.0040, 0.9960]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9385, 0.0615],
        [0.9374, 0.0626],
        [0.9435, 0.0565],
        [0.9653, 0.0347],
        [0.3285, 0.6715],
        [0.6036, 0.3964],
        [0.3802, 0.6198],
        [0.2748, 0.7252]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


4it [00:00,  4.25it/s]

tensor([[0.0260, 0.9740],
        [0.0322, 0.9678],
        [0.0365, 0.9635],
        [0.0145, 0.9855],
        [0.6518, 0.3482],
        [0.6515, 0.3485],
        [0.0132, 0.9868],
        [0.0191, 0.9809]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0525, 0.9475],
        [0.0109, 0.9891],
        [0.0234, 0.9766],
        [0.9634, 0.0366],
        [0.9348, 0.0652],
        [0.6472, 0.3528],
        [0.8188, 0.1812],
        [0.8080, 0.1920]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


6it [00:00,  5.37it/s]

tensor([[0.0013, 0.9987],
        [0.0014, 0.9986],
        [0.0024, 0.9976],
        [0.0012, 0.9988],
        [0.0423, 0.9577],
        [0.7375, 0.2625],
        [0.7416, 0.2584],
        [0.7208, 0.2792]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9034, 0.0966],
        [0.9267, 0.0733],
        [0.8771, 0.1229],
        [0.7441, 0.2559],
        [0.4904, 0.5096],
        [0.9198, 0.0802],
        [0.0305, 0.9695],
        [0.0498, 0.9502]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0293, 0.9707],
        [0.0342, 0.9658],
        [0.0191, 0.9809],
        [0.0120, 0.9880],
        [0.0222, 0.9778],
        [0.0066, 0.9934],
        [0.2033, 0.7967],
        [0.5628, 0.4372]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


10it [00:01,  7.63it/s]

tensor([[0.1711, 0.8289],
        [0.0673, 0.9327],
        [0.5364, 0.4636],
        [0.6653, 0.3347],
        [0.7986, 0.2014],
        [0.4342, 0.5658],
        [0.8039, 0.1961],
        [0.0224, 0.9776]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0039, 0.9961],
        [0.2503, 0.7497],
        [0.6716, 0.3284],
        [0.2393, 0.7607],
        [0.6622, 0.3378],
        [0.4888, 0.5112],
        [0.3169, 0.6831],
        [0.0568, 0.9432]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.1844, 0.8156],
        [0.0135, 0.9865],
        [0.1673, 0.8327],
        [0.0044, 0.9956],
        [0.1888, 0.8112],
        [0.0556, 0.9444],
        [0.0698, 0.9302],
        [0.1208, 0.8792]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


12it [00:01,  8.46it/s]

tensor([[1.3688e-03, 9.9863e-01],
        [7.3014e-04, 9.9927e-01],
        [7.2387e-02, 9.2761e-01],
        [3.0055e-01, 6.9945e-01],
        [2.2420e-01, 7.7580e-01],
        [3.5477e-03, 9.9645e-01],
        [2.8083e-02, 9.7192e-01],
        [1.8102e-03, 9.9819e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0016, 0.9984],
        [0.0542, 0.9458],
        [0.1612, 0.8388],
        [0.0482, 0.9518],
        [0.0161, 0.9839],
        [0.0069, 0.9931],
        [0.0082, 0.9918],
        [0.0043, 0.9957]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0062, 0.9938],
        [0.9092, 0.0908],
        [0.8780, 0.1220],
        [0.8678, 0.1322],
        [0.9196, 0.0804],
        [0.8059, 0.1941],
        [0.0025, 0.9975],
        [0.0222, 0.9778]], device='cuda:0')
tensor([1, 0, 0, 0, 1, 1, 1, 1])


16it [00:01, 10.19it/s]

tensor([[0.5251, 0.4749],
        [0.9018, 0.0982],
        [0.7478, 0.2522],
        [0.7296, 0.2704],
        [0.4091, 0.5909],
        [0.8554, 0.1446],
        [0.5171, 0.4829],
        [0.0164, 0.9836]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0752, 0.9248],
        [0.0286, 0.9714],
        [0.4159, 0.5841],
        [0.0301, 0.9699],
        [0.0305, 0.9695],
        [0.0569, 0.9431],
        [0.2164, 0.7836],
        [0.0460, 0.9540]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.1408, 0.8592],
        [0.1097, 0.8903],
        [0.1890, 0.8110],
        [0.5562, 0.4438],
        [0.5970, 0.4030],
        [0.7600, 0.2400],
        [0.6535, 0.3465],
        [0.6139, 0.3861]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


18it [00:01, 10.60it/s]

tensor([[0.0167, 0.9833],
        [0.0621, 0.9379],
        [0.5827, 0.4173],
        [0.7401, 0.2599],
        [0.6208, 0.3792],
        [0.0024, 0.9976],
        [0.0032, 0.9968],
        [0.0011, 0.9989]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0020, 0.9980],
        [0.0090, 0.9910],
        [0.1873, 0.8127],
        [0.0684, 0.9316],
        [0.3812, 0.6188],
        [0.6013, 0.3987],
        [0.5128, 0.4872],
        [0.8415, 0.1585]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.8861, 0.1139],
        [0.9530, 0.0470],
        [0.9591, 0.0409],
        [0.0106, 0.9894],
        [0.0154, 0.9846],
        [0.0187, 0.9813],
        [0.0223, 0.9777],
        [0.0372, 0.9628]], device='cuda:0')
tensor([1, 0, 0, 1, 1, 1, 1, 1])


22it [00:02, 11.42it/s]

tensor([[2.8378e-03, 9.9716e-01],
        [2.0431e-02, 9.7957e-01],
        [8.1163e-03, 9.9188e-01],
        [1.1409e-02, 9.8859e-01],
        [5.6701e-01, 4.3299e-01],
        [8.1445e-01, 1.8555e-01],
        [4.1318e-04, 9.9959e-01],
        [1.3978e-03, 9.9860e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[2.8799e-03, 9.9712e-01],
        [2.4546e-04, 9.9975e-01],
        [4.0900e-03, 9.9591e-01],
        [9.4730e-01, 5.2704e-02],
        [1.2796e-01, 8.7204e-01],
        [5.7725e-02, 9.4227e-01],
        [1.7160e-01, 8.2840e-01],
        [1.7633e-02, 9.8237e-01]], device='cuda:0')
tensor([1, 1, 1, 0, 1, 1, 1, 1])
tensor([[0.0055, 0.9945],
        [0.0171, 0.9829],
        [0.9305, 0.0695],
        [0.5690, 0.4310],
        [0.6552, 0.3448],
        [0.1783, 0.8217],
        [0.1613, 0.8387],
        [0.4364, 0.5636]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


24it [00:02, 11.50it/s]

tensor([[0.9224, 0.0776],
        [0.2248, 0.7752],
        [0.2357, 0.7643],
        [0.0561, 0.9439],
        [0.1413, 0.8587],
        [0.5927, 0.4073],
        [0.7075, 0.2925],
        [0.8939, 0.1061]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.6169, 0.3831],
        [0.7530, 0.2470],
        [0.2789, 0.7211],
        [0.6437, 0.3563],
        [0.0546, 0.9454],
        [0.0476, 0.9524],
        [0.0458, 0.9542],
        [0.2050, 0.7950]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0970, 0.9030],
        [0.6016, 0.3984],
        [0.7509, 0.2491],
        [0.5782, 0.4218],
        [0.7697, 0.2303],
        [0.8252, 0.1748],
        [0.5160, 0.4840],
        [0.7000, 0.3000]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


28it [00:02, 11.68it/s]

tensor([[0.5686, 0.4314],
        [0.6665, 0.3335],
        [0.5628, 0.4372],
        [0.7178, 0.2822],
        [0.5444, 0.4556],
        [0.7221, 0.2779],
        [0.6824, 0.3176],
        [0.7683, 0.2317]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.6154, 0.3846],
        [0.0693, 0.9307],
        [0.0440, 0.9560],
        [0.0619, 0.9381],
        [0.0379, 0.9621],
        [0.0231, 0.9769],
        [0.0460, 0.9540],
        [0.0533, 0.9467]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0535, 0.9465],
        [0.0191, 0.9809],
        [0.0239, 0.9761],
        [0.0015, 0.9985],
        [0.0094, 0.9906],
        [0.0216, 0.9784],
        [0.1725, 0.8275],
        [0.0520, 0.9480]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


30it [00:02, 11.23it/s]

tensor([[0.0372, 0.9628],
        [0.0332, 0.9668],
        [0.1091, 0.8909],
        [0.1946, 0.8054],
        [0.2118, 0.7882],
        [0.1157, 0.8843],
        [0.3731, 0.6269],
        [0.7662, 0.2338]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.8968, 0.1032],
        [0.9156, 0.0844],
        [0.9356, 0.0644],
        [0.9726, 0.0274],
        [0.9343, 0.0657],
        [0.9083, 0.0917],
        [0.6207, 0.3793],
        [0.5342, 0.4658]], device='cuda:0')
tensor([1, 1, 1, 1, 0, 0, 0, 0])
tensor([[0.9488, 0.0512],
        [0.9704, 0.0296],
        [0.9769, 0.0231],
        [0.9828, 0.0172],
        [0.9864, 0.0136],
        [0.9047, 0.0953],
        [0.9118, 0.0882],
        [0.7744, 0.2256]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


34it [00:03, 12.08it/s]

tensor([[0.8817, 0.1183],
        [0.7494, 0.2506],
        [0.9381, 0.0619],
        [0.8887, 0.1113],
        [0.9470, 0.0530],
        [0.9374, 0.0626],
        [0.9631, 0.0369],
        [0.9346, 0.0654]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9417, 0.0583],
        [0.8683, 0.1317],
        [0.9447, 0.0553],
        [0.8725, 0.1275],
        [0.8220, 0.1780],
        [0.9449, 0.0551],
        [0.9697, 0.0303],
        [0.9429, 0.0571]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9506, 0.0494],
        [0.9610, 0.0390],
        [0.9682, 0.0318],
        [0.9328, 0.0672],
        [0.8357, 0.1643],
        [0.8621, 0.1379],
        [0.8165, 0.1835],
        [0.9774, 0.0226]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


36it [00:03, 11.41it/s]

tensor([[0.9828, 0.0172],
        [0.9643, 0.0357],
        [0.7760, 0.2240],
        [0.9212, 0.0788],
        [0.8718, 0.1282],
        [0.9418, 0.0582],
        [0.8294, 0.1706],
        [0.9623, 0.0377]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8617, 0.1383],
        [0.8106, 0.1894],
        [0.9277, 0.0723],
        [0.7853, 0.2147],
        [0.8523, 0.1477],
        [0.9376, 0.0624],
        [0.9330, 0.0670],
        [0.8219, 0.1781]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6568, 0.3432],
        [0.7542, 0.2458],
        [0.6338, 0.3662],
        [0.6814, 0.3186],
        [0.9237, 0.0763],
        [0.9650, 0.0350],
        [0.9748, 0.0252],
        [0.9859, 0.0141]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


40it [00:03, 11.64it/s]

tensor([[0.9690, 0.0310],
        [0.7002, 0.2998],
        [0.7674, 0.2326],
        [0.9633, 0.0367],
        [0.9435, 0.0565],
        [0.9361, 0.0639],
        [0.1487, 0.8513],
        [0.1576, 0.8424]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8539, 0.1461],
        [0.7625, 0.2375],
        [0.8562, 0.1438],
        [0.8894, 0.1106],
        [0.8353, 0.1647],
        [0.7760, 0.2240],
        [0.8507, 0.1493],
        [0.8240, 0.1760]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.5797, 0.4203],
        [0.0286, 0.9714],
        [0.0511, 0.9489],
        [0.9303, 0.0697],
        [0.9038, 0.0962],
        [0.9357, 0.0643],
        [0.9556, 0.0444],
        [0.9191, 0.0809]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


42it [00:03, 11.55it/s]

tensor([[0.9227, 0.0773],
        [0.9263, 0.0737],
        [0.9578, 0.0422],
        [0.7171, 0.2829],
        [0.7208, 0.2792],
        [0.7991, 0.2009],
        [0.7883, 0.2117],
        [0.9358, 0.0642]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9222, 0.0778],
        [0.8424, 0.1576],
        [0.9235, 0.0765],
        [0.9350, 0.0650],
        [0.6199, 0.3801],
        [0.9134, 0.0866],
        [0.6774, 0.3226],
        [0.7402, 0.2598]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6544, 0.3456],
        [0.7441, 0.2559],
        [0.6204, 0.3796],
        [0.6599, 0.3401],
        [0.8393, 0.1607],
        [0.7696, 0.2304],
        [0.9273, 0.0727],
        [0.8825, 0.1175]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


46it [00:04, 11.58it/s]

tensor([[0.9342, 0.0658],
        [0.9486, 0.0514],
        [0.8251, 0.1749],
        [0.8604, 0.1396],
        [0.9498, 0.0502],
        [0.9155, 0.0845],
        [0.9477, 0.0523],
        [0.9580, 0.0420]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9578, 0.0422],
        [0.8893, 0.1107],
        [0.8934, 0.1066],
        [0.9237, 0.0763],
        [0.9580, 0.0420],
        [0.9472, 0.0528],
        [0.7963, 0.2037],
        [0.7457, 0.2543]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7395, 0.2605],
        [0.6882, 0.3118],
        [0.6573, 0.3427],
        [0.7330, 0.2670],
        [0.7106, 0.2894],
        [0.6762, 0.3238],
        [0.6522, 0.3478],
        [0.7061, 0.2939]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


48it [00:04, 11.89it/s]

tensor([[0.6628, 0.3372],
        [0.5912, 0.4088],
        [0.4847, 0.5153],
        [0.6302, 0.3698],
        [0.8088, 0.1912],
        [0.9352, 0.0648],
        [0.9342, 0.0658],
        [0.9451, 0.0549]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.5846, 0.4154],
        [0.6414, 0.3586],
        [0.6182, 0.3818],
        [0.6105, 0.3895],
        [0.9601, 0.0399],
        [0.9156, 0.0844],
        [0.4512, 0.5488],
        [0.1575, 0.8425]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9597, 0.0403],
        [0.9463, 0.0537],
        [0.9141, 0.0859],
        [0.6892, 0.3108],
        [0.6007, 0.3993],
        [0.7166, 0.2834],
        [0.7316, 0.2684],
        [0.8948, 0.1052]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


52it [00:04, 12.42it/s]

tensor([[0.7822, 0.2178],
        [0.7759, 0.2241],
        [0.9024, 0.0976],
        [0.7623, 0.2377],
        [0.8274, 0.1726],
        [0.9233, 0.0767],
        [0.9413, 0.0587],
        [0.7276, 0.2724]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8718, 0.1282],
        [0.9160, 0.0840],
        [0.4604, 0.5396],
        [0.3182, 0.6818],
        [0.4126, 0.5874],
        [0.8995, 0.1005],
        [0.9710, 0.0290],
        [0.8174, 0.1826]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7411, 0.2589],
        [0.6958, 0.3042],
        [0.8150, 0.1850],
        [0.9691, 0.0309],
        [0.9499, 0.0501],
        [0.9371, 0.0629],
        [0.6684, 0.3316],
        [0.7309, 0.2691]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


54it [00:04, 12.89it/s]

tensor([[0.7451, 0.2549],
        [0.7891, 0.2109],
        [0.4710, 0.5290],
        [0.9764, 0.0236],
        [0.9704, 0.0296],
        [0.9178, 0.0822],
        [0.9339, 0.0661],
        [0.8451, 0.1549]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9643, 0.0357],
        [0.9043, 0.0957],
        [0.9676, 0.0324],
        [0.9608, 0.0392],
        [0.9517, 0.0483],
        [0.8912, 0.1088],
        [0.9685, 0.0315],
        [0.9512, 0.0488]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9582, 0.0418],
        [0.6115, 0.3885],
        [0.6856, 0.3144],
        [0.6252, 0.3748],
        [0.7363, 0.2637],
        [0.7106, 0.2894],
        [0.8144, 0.1856],
        [0.6922, 0.3078]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


58it [00:05, 13.59it/s]

tensor([[0.9034, 0.0966],
        [0.9237, 0.0763],
        [0.7056, 0.2944],
        [0.7441, 0.2559],
        [0.7194, 0.2806],
        [0.6600, 0.3400],
        [0.9650, 0.0350],
        [0.9504, 0.0496]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8986, 0.1014],
        [0.9353, 0.0647],
        [0.8166, 0.1834],
        [0.7657, 0.2343],
        [0.7163, 0.2837],
        [0.6810, 0.3190],
        [0.6276, 0.3724],
        [0.7409, 0.2591]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8999, 0.1001],
        [0.8936, 0.1064],
        [0.7826, 0.2174],
        [0.8069, 0.1931],
        [0.8688, 0.1312],
        [0.9139, 0.0861],
        [0.8459, 0.1541],
        [0.9505, 0.0495]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([0.9415, 0.0585], device='cuda:0')
tensor([0])
Error : number of targets and predicted outputs do not match


59it [00:05, 10.99it/s]

val_accuracy:  80.38793103448276
epoch:1,lr:0.0001,loss:0.4526205360889435,train_cm:[[2734  191]
 [ 882 1124]],val_cm:[[223  11]
 [ 80 150]],train_acc:78.2397079699858, val_acc:80.38793103448276



617it [02:43,  3.78it/s]
2it [00:00,  3.17it/s]

tensor([[0.1027, 0.8973],
        [0.0678, 0.9322],
        [0.1413, 0.8587],
        [0.0566, 0.9434],
        [0.0306, 0.9694],
        [0.0382, 0.9618],
        [0.0578, 0.9422],
        [0.0551, 0.9449]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9220, 0.0780],
        [0.9205, 0.0795],
        [0.9213, 0.0787],
        [0.8405, 0.1595],
        [0.2481, 0.7519],
        [0.5488, 0.4512],
        [0.2717, 0.7283],
        [0.1520, 0.8480]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


4it [00:00,  4.41it/s]

tensor([[0.0594, 0.9406],
        [0.0495, 0.9505],
        [0.1877, 0.8123],
        [0.0566, 0.9434],
        [0.6466, 0.3534],
        [0.3037, 0.6963],
        [0.1188, 0.8812],
        [0.2099, 0.7901]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0577, 0.9423],
        [0.1608, 0.8392],
        [0.1349, 0.8651],
        [0.9527, 0.0473],
        [0.9011, 0.0989],
        [0.1137, 0.8863],
        [0.1564, 0.8436],
        [0.3369, 0.6631]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


6it [00:00,  5.52it/s]

tensor([[0.0030, 0.9970],
        [0.0100, 0.9900],
        [0.0266, 0.9734],
        [0.0310, 0.9690],
        [0.0831, 0.9169],
        [0.8893, 0.1107],
        [0.8971, 0.1029],
        [0.6953, 0.3047]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9401, 0.0599],
        [0.8814, 0.1186],
        [0.8309, 0.1691],
        [0.8429, 0.1571],
        [0.1360, 0.8640],
        [0.7518, 0.2482],
        [0.0197, 0.9803],
        [0.0578, 0.9422]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.2164, 0.7836],
        [0.0814, 0.9186],
        [0.0898, 0.9102],
        [0.1190, 0.8810],
        [0.0957, 0.9043],
        [0.0904, 0.9096],
        [0.6477, 0.3523],
        [0.4669, 0.5331]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


10it [00:01,  7.80it/s]

tensor([[0.2850, 0.7150],
        [0.3291, 0.6709],
        [0.7212, 0.2788],
        [0.6561, 0.3439],
        [0.7342, 0.2658],
        [0.7790, 0.2210],
        [0.6444, 0.3556],
        [0.0173, 0.9827]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0032, 0.9968],
        [0.0286, 0.9714],
        [0.1313, 0.8687],
        [0.0477, 0.9523],
        [0.5434, 0.4566],
        [0.0852, 0.9148],
        [0.1319, 0.8681],
        [0.2228, 0.7772]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.2380, 0.7620],
        [0.1881, 0.8119],
        [0.3029, 0.6971],
        [0.1781, 0.8219],
        [0.3398, 0.6602],
        [0.1865, 0.8135],
        [0.1926, 0.8074],
        [0.2961, 0.7039]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


12it [00:01,  8.83it/s]

tensor([[0.0868, 0.9132],
        [0.0527, 0.9473],
        [0.4455, 0.5545],
        [0.6849, 0.3151],
        [0.7574, 0.2426],
        [0.1347, 0.8653],
        [0.1083, 0.8917],
        [0.0817, 0.9183]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.1131, 0.8869],
        [0.0265, 0.9735],
        [0.0472, 0.9528],
        [0.0281, 0.9719],
        [0.1463, 0.8537],
        [0.1504, 0.8496],
        [0.1081, 0.8919],
        [0.0927, 0.9073]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0926, 0.9074],
        [0.9292, 0.0708],
        [0.8319, 0.1681],
        [0.9306, 0.0694],
        [0.6804, 0.3196],
        [0.6960, 0.3040],
        [0.0496, 0.9504],
        [0.2177, 0.7823]], device='cuda:0')
tensor([1, 0, 0, 0, 1, 1, 1, 1])


16it [00:01, 10.45it/s]

tensor([[0.3778, 0.6222],
        [0.8627, 0.1373],
        [0.6548, 0.3452],
        [0.7449, 0.2551],
        [0.2852, 0.7148],
        [0.6771, 0.3229],
        [0.5156, 0.4844],
        [0.1340, 0.8660]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.3415, 0.6585],
        [0.2941, 0.7059],
        [0.3224, 0.6776],
        [0.1561, 0.8439],
        [0.1757, 0.8243],
        [0.1335, 0.8665],
        [0.2375, 0.7625],
        [0.3157, 0.6843]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.2621, 0.7379],
        [0.2844, 0.7156],
        [0.3521, 0.6479],
        [0.7949, 0.2051],
        [0.7677, 0.2323],
        [0.5932, 0.4068],
        [0.9093, 0.0907],
        [0.8786, 0.1214]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


18it [00:01, 10.34it/s]

tensor([[0.3007, 0.6993],
        [0.4642, 0.5358],
        [0.8701, 0.1299],
        [0.7172, 0.2828],
        [0.6890, 0.3110],
        [0.0504, 0.9496],
        [0.0591, 0.9409],
        [0.0181, 0.9819]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0765, 0.9235],
        [0.0716, 0.9284],
        [0.0134, 0.9866],
        [0.0190, 0.9810],
        [0.2416, 0.7584],
        [0.4985, 0.5015],
        [0.3890, 0.6110],
        [0.8470, 0.1530]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9661, 0.0339],
        [0.7735, 0.2265],
        [0.9054, 0.0946],
        [0.1723, 0.8277],
        [0.1806, 0.8194],
        [0.1715, 0.8285],
        [0.0536, 0.9464],
        [0.2607, 0.7393]], device='cuda:0')
tensor([1, 0, 0, 1, 1, 1, 1, 1])


22it [00:02, 11.64it/s]

tensor([[0.1142, 0.8858],
        [0.1511, 0.8489],
        [0.0832, 0.9168],
        [0.1052, 0.8948],
        [0.3109, 0.6891],
        [0.6184, 0.3816],
        [0.0569, 0.9431],
        [0.0547, 0.9453]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0841, 0.9159],
        [0.0163, 0.9837],
        [0.0574, 0.9426],
        [0.9262, 0.0738],
        [0.4333, 0.5667],
        [0.3550, 0.6450],
        [0.5891, 0.4109],
        [0.1506, 0.8494]], device='cuda:0')
tensor([1, 1, 1, 0, 1, 1, 1, 1])
tensor([[0.0162, 0.9838],
        [0.0167, 0.9833],
        [0.4825, 0.5175],
        [0.3787, 0.6213],
        [0.2508, 0.7492],
        [0.1591, 0.8409],
        [0.0909, 0.9091],
        [0.1531, 0.8469]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


24it [00:02, 11.88it/s]

tensor([[0.5383, 0.4617],
        [0.2371, 0.7629],
        [0.1173, 0.8827],
        [0.0035, 0.9965],
        [0.0099, 0.9901],
        [0.2798, 0.7202],
        [0.6757, 0.3243],
        [0.5605, 0.4395]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.3254, 0.6746],
        [0.3085, 0.6915],
        [0.2580, 0.7420],
        [0.3488, 0.6512],
        [0.2740, 0.7260],
        [0.2371, 0.7629],
        [0.1976, 0.8024],
        [0.4654, 0.5346]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0740, 0.9260],
        [0.6660, 0.3340],
        [0.4111, 0.5889],
        [0.5036, 0.4964],
        [0.5995, 0.4005],
        [0.7520, 0.2480],
        [0.8320, 0.1680],
        [0.7222, 0.2778]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


28it [00:02, 11.58it/s]

tensor([[0.5800, 0.4200],
        [0.6652, 0.3348],
        [0.6094, 0.3906],
        [0.7945, 0.2055],
        [0.8287, 0.1713],
        [0.7420, 0.2580],
        [0.8494, 0.1506],
        [0.6030, 0.3970]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.8679, 0.1321],
        [0.3988, 0.6012],
        [0.1492, 0.8508],
        [0.4141, 0.5859],
        [0.2296, 0.7704],
        [0.2002, 0.7998],
        [0.2229, 0.7771],
        [0.2649, 0.7351]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.2004, 0.7996],
        [0.1982, 0.8018],
        [0.2254, 0.7746],
        [0.0925, 0.9075],
        [0.1309, 0.8691],
        [0.2268, 0.7732],
        [0.2583, 0.7417],
        [0.3051, 0.6949]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


30it [00:02, 11.42it/s]

tensor([[0.1896, 0.8104],
        [0.2271, 0.7729],
        [0.5464, 0.4536],
        [0.5982, 0.4018],
        [0.1286, 0.8714],
        [0.4649, 0.5351],
        [0.1810, 0.8190],
        [0.9038, 0.0962]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9731, 0.0269],
        [0.9571, 0.0429],
        [0.8672, 0.1328],
        [0.9363, 0.0637],
        [0.8727, 0.1273],
        [0.9234, 0.0766],
        [0.3550, 0.6450],
        [0.2182, 0.7818]], device='cuda:0')
tensor([1, 1, 1, 1, 0, 0, 0, 0])
tensor([[0.9170, 0.0830],
        [0.9749, 0.0251],
        [0.9165, 0.0835],
        [0.9659, 0.0341],
        [0.9771, 0.0229],
        [0.9221, 0.0779],
        [0.9339, 0.0661],
        [0.9164, 0.0836]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


34it [00:03, 11.14it/s]

tensor([[0.8369, 0.1631],
        [0.8691, 0.1309],
        [0.9415, 0.0585],
        [0.9719, 0.0281],
        [0.9248, 0.0752],
        [0.9114, 0.0886],
        [0.9447, 0.0553],
        [0.8696, 0.1304]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9405, 0.0595],
        [0.9090, 0.0910],
        [0.8609, 0.1391],
        [0.9406, 0.0594],
        [0.8185, 0.1815],
        [0.9545, 0.0455],
        [0.9381, 0.0619],
        [0.9222, 0.0778]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9370, 0.0630],
        [0.9576, 0.0424],
        [0.9540, 0.0460],
        [0.8876, 0.1124],
        [0.9258, 0.0742],
        [0.8886, 0.1114],
        [0.8636, 0.1364],
        [0.9661, 0.0339]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


36it [00:03, 10.78it/s]

tensor([[0.9723, 0.0277],
        [0.9428, 0.0572],
        [0.6694, 0.3306],
        [0.8267, 0.1733],
        [0.9409, 0.0591],
        [0.9371, 0.0629],
        [0.6457, 0.3543],
        [0.8875, 0.1125]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.4859, 0.5141],
        [0.7856, 0.2144],
        [0.8618, 0.1382],
        [0.8510, 0.1490],
        [0.9513, 0.0487],
        [0.9438, 0.0562],
        [0.8936, 0.1064],
        [0.7892, 0.2108]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


38it [00:03, 11.26it/s]

tensor([[0.8747, 0.1253],
        [0.6384, 0.3616],
        [0.8741, 0.1259],
        [0.8454, 0.1546],
        [0.9338, 0.0662],
        [0.9645, 0.0355],
        [0.9673, 0.0327],
        [0.9594, 0.0406]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9512, 0.0488],
        [0.8521, 0.1479],
        [0.7316, 0.2684],
        [0.9467, 0.0533],
        [0.9378, 0.0622],
        [0.9586, 0.0414],
        [0.3487, 0.6513],
        [0.1585, 0.8415]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9489, 0.0511],
        [0.6967, 0.3033],
        [0.9418, 0.0582],
        [0.6097, 0.3903],
        [0.6246, 0.3754],
        [0.6723, 0.3277],
        [0.8406, 0.1594],
        [0.8949, 0.1051]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


42it [00:03, 11.89it/s]

tensor([[0.5778, 0.4222],
        [0.0456, 0.9544],
        [0.1840, 0.8160],
        [0.4847, 0.5153],
        [0.5432, 0.4568],
        [0.9708, 0.0292],
        [0.9599, 0.0401],
        [0.9555, 0.0445]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9070, 0.0930],
        [0.9503, 0.0497],
        [0.9666, 0.0334],
        [0.6613, 0.3387],
        [0.0805, 0.9195],
        [0.8598, 0.1402],
        [0.9276, 0.0724],
        [0.9071, 0.0929]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9196, 0.0804],
        [0.7346, 0.2654],
        [0.8746, 0.1254],
        [0.7643, 0.2357],
        [0.2184, 0.7816],
        [0.6376, 0.3624],
        [0.9726, 0.0274],
        [0.7540, 0.2460]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


44it [00:04, 12.29it/s]

tensor([[0.6165, 0.3835],
        [0.7292, 0.2708],
        [0.3389, 0.6611],
        [0.4592, 0.5408],
        [0.7786, 0.2214],
        [0.8069, 0.1931],
        [0.7982, 0.2018],
        [0.6568, 0.3432]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8093, 0.1907],
        [0.8372, 0.1628],
        [0.8415, 0.1585],
        [0.9143, 0.0857],
        [0.9562, 0.0438],
        [0.8868, 0.1132],
        [0.9529, 0.0471],
        [0.9327, 0.0673]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8937, 0.1063],
        [0.8439, 0.1561],
        [0.7914, 0.2086],
        [0.9284, 0.0716],
        [0.9035, 0.0965],
        [0.8940, 0.1060],
        [0.8203, 0.1797],
        [0.8985, 0.1015]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


48it [00:04, 12.28it/s]

tensor([[0.2890, 0.7110],
        [0.6322, 0.3678],
        [0.8359, 0.1641],
        [0.4912, 0.5088],
        [0.8586, 0.1414],
        [0.8836, 0.1164],
        [0.7617, 0.2383],
        [0.8863, 0.1137]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8125, 0.1875],
        [0.8912, 0.1088],
        [0.8182, 0.1818],
        [0.8598, 0.1402],
        [0.7918, 0.2082],
        [0.8265, 0.1735],
        [0.8585, 0.1415],
        [0.8833, 0.1167]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7479, 0.2521],
        [0.7628, 0.2372],
        [0.8786, 0.1214],
        [0.6682, 0.3318],
        [0.9828, 0.0172],
        [0.9245, 0.0755],
        [0.6182, 0.3818],
        [0.0891, 0.9109]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


50it [00:04, 12.00it/s]

tensor([[0.9667, 0.0333],
        [0.9119, 0.0881],
        [0.9269, 0.0731],
        [0.8538, 0.1462],
        [0.7906, 0.2094],
        [0.8799, 0.1201],
        [0.5473, 0.4527],
        [0.9154, 0.0846]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9286, 0.0714],
        [0.8875, 0.1125],
        [0.8006, 0.1994],
        [0.7678, 0.2322],
        [0.4535, 0.5465],
        [0.9374, 0.0626],
        [0.9120, 0.0880],
        [0.1673, 0.8327]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


52it [00:04, 12.25it/s]

tensor([[0.7104, 0.2896],
        [0.8055, 0.1945],
        [0.5543, 0.4457],
        [0.4737, 0.5263],
        [0.8217, 0.1783],
        [0.5951, 0.4049],
        [0.8857, 0.1143],
        [0.8109, 0.1891]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8590, 0.1410],
        [0.8716, 0.1284],
        [0.8699, 0.1301],
        [0.9418, 0.0582],
        [0.8852, 0.1148],
        [0.9310, 0.0690],
        [0.7321, 0.2679],
        [0.7904, 0.2096]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8455, 0.1545],
        [0.7440, 0.2560],
        [0.7959, 0.2041],
        [0.9205, 0.0795],
        [0.9265, 0.0735],
        [0.9606, 0.0394],
        [0.9773, 0.0227],
        [0.8848, 0.1152]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


56it [00:05, 13.23it/s]

tensor([[0.9467, 0.0533],
        [0.9417, 0.0583],
        [0.9564, 0.0436],
        [0.8481, 0.1519],
        [0.7544, 0.2456],
        [0.7404, 0.2596],
        [0.9701, 0.0299],
        [0.9537, 0.0463]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8879, 0.1121],
        [0.8555, 0.1445],
        [0.5623, 0.4377],
        [0.8137, 0.1863],
        [0.8467, 0.1533],
        [0.8634, 0.1366],
        [0.3080, 0.6920],
        [0.9037, 0.0963]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9495, 0.0505],
        [0.8517, 0.1483],
        [0.6325, 0.3675],
        [0.5369, 0.4631],
        [0.7593, 0.2407],
        [0.7390, 0.2610],
        [0.9741, 0.0259],
        [0.9827, 0.0173]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


58it [00:05, 13.62it/s]

tensor([[0.9176, 0.0824],
        [0.9011, 0.0989],
        [0.7424, 0.2576],
        [0.8724, 0.1276],
        [0.5190, 0.4810],
        [0.8379, 0.1621],
        [0.8765, 0.1235],
        [0.2880, 0.7120]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.5626, 0.4374],
        [0.8489, 0.1511],
        [0.8018, 0.1982],
        [0.7547, 0.2453],
        [0.8517, 0.1483],
        [0.6424, 0.3576],
        [0.6754, 0.3246],
        [0.9046, 0.0954]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([0.9124, 0.0876], device='cuda:0')
tensor([0])
Error : number of targets and predicted outputs do not match


59it [00:05, 10.98it/s]

val_accuracy:  80.81896551724138
epoch:2,lr:0.0001,loss:0.42131972312927246,train_cm:[[2750  175]
 [ 790 1216]],val_cm:[[214  20]
 [ 69 161]],train_acc:80.42993307645509, val_acc:80.81896551724138



617it [02:43,  3.78it/s]
2it [00:00,  2.90it/s]

tensor([[0.0023, 0.9977],
        [0.0028, 0.9972],
        [0.0106, 0.9894],
        [0.0018, 0.9982],
        [0.0019, 0.9981],
        [0.0019, 0.9981],
        [0.0477, 0.9523],
        [0.0019, 0.9981]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.4601, 0.5399],
        [0.5934, 0.4066],
        [0.7358, 0.2642],
        [0.7113, 0.2887],
        [0.4222, 0.5778],
        [0.5364, 0.4636],
        [0.5648, 0.4352],
        [0.2599, 0.7401]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


5it [00:00,  4.51it/s]

tensor([[0.0031, 0.9969],
        [0.0188, 0.9812],
        [0.0142, 0.9858],
        [0.0029, 0.9971],
        [0.6041, 0.3959],
        [0.5213, 0.4787],
        [0.0263, 0.9737],
        [0.1003, 0.8997]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0120, 0.9880],
        [0.0106, 0.9894],
        [0.0070, 0.9930],
        [0.8990, 0.1010],
        [0.7709, 0.2291],
        [0.0498, 0.9502],
        [0.1019, 0.8981],
        [0.2297, 0.7703]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[3.1240e-05, 9.9997e-01],
        [6.9495e-05, 9.9993e-01],
        [1.6128e-04, 9.9984e-01],
        [5.0075e-05, 9.9995e-01],
        [2.7127e-04, 9.9973e-01],
        [8.0365e-01, 1.9635e-01],
        [7.9447e-01, 2.0553e-01],
        [8.1558e-01, 1.8442e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


8it [00:01,  6.49it/s]

tensor([[8.1868e-01, 1.8132e-01],
        [7.0080e-01, 2.9920e-01],
        [8.9496e-01, 1.0504e-01],
        [8.0848e-01, 1.9152e-01],
        [2.1244e-02, 9.7876e-01],
        [7.1031e-01, 2.8969e-01],
        [3.1688e-04, 9.9968e-01],
        [3.2052e-03, 9.9679e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[7.3941e-03, 9.9261e-01],
        [4.4086e-04, 9.9956e-01],
        [7.7716e-04, 9.9922e-01],
        [2.3531e-04, 9.9976e-01],
        [5.1301e-04, 9.9949e-01],
        [1.0408e-03, 9.9896e-01],
        [5.6183e-01, 4.3817e-01],
        [1.0641e-01, 8.9359e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0027, 0.9973],
        [0.0292, 0.9708],
        [0.6557, 0.3443],
        [0.6186, 0.3814],
        [0.8222, 0.1778],
        [0.6052, 0.3948],
        [0.6889, 0.3111],
        [0.0147, 0.9853]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


11it [00:01,  8.36it/s]

tensor([[1.7493e-04, 9.9983e-01],
        [9.9846e-02, 9.0015e-01],
        [1.7059e-01, 8.2941e-01],
        [3.4298e-02, 9.6570e-01],
        [7.4602e-01, 2.5398e-01],
        [1.4996e-01, 8.5004e-01],
        [2.7142e-02, 9.7286e-01],
        [6.0628e-03, 9.9394e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0047, 0.9953],
        [0.0093, 0.9907],
        [0.0148, 0.9852],
        [0.0165, 0.9835],
        [0.0125, 0.9875],
        [0.0034, 0.9966],
        [0.0042, 0.9958],
        [0.0057, 0.9943]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[8.6059e-04, 9.9914e-01],
        [8.2372e-04, 9.9918e-01],
        [1.4488e-02, 9.8551e-01],
        [3.2852e-02, 9.6715e-01],
        [5.7818e-02, 9.4218e-01],
        [5.8531e-03, 9.9415e-01],
        [1.1055e-02, 9.8894e-01],
        [2.8515e-03, 9.9715e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


13it [00:01,  9.35it/s]

tensor([[0.0059, 0.9941],
        [0.1242, 0.8758],
        [0.1744, 0.8256],
        [0.0330, 0.9670],
        [0.0055, 0.9945],
        [0.0053, 0.9947],
        [0.0059, 0.9941],
        [0.0039, 0.9961]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0035, 0.9965],
        [0.9318, 0.0682],
        [0.8884, 0.1116],
        [0.9243, 0.0757],
        [0.5359, 0.4641],
        [0.5613, 0.4387],
        [0.0033, 0.9967],
        [0.0073, 0.9927]], device='cuda:0')
tensor([1, 0, 0, 0, 1, 1, 1, 1])
tensor([[0.3621, 0.6379],
        [0.8142, 0.1858],
        [0.7305, 0.2695],
        [0.6555, 0.3445],
        [0.4732, 0.5268],
        [0.7155, 0.2845],
        [0.6686, 0.3314],
        [0.0091, 0.9909]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


17it [00:01, 10.97it/s]

tensor([[0.0217, 0.9783],
        [0.0101, 0.9899],
        [0.4255, 0.5745],
        [0.0095, 0.9905],
        [0.0075, 0.9925],
        [0.0166, 0.9834],
        [0.0140, 0.9860],
        [0.0076, 0.9924]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0179, 0.9821],
        [0.0079, 0.9921],
        [0.0082, 0.9918],
        [0.5925, 0.4075],
        [0.5519, 0.4481],
        [0.7980, 0.2020],
        [0.0828, 0.9172],
        [0.0663, 0.9337]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[5.0111e-03, 9.9499e-01],
        [3.1914e-02, 9.6809e-01],
        [9.9299e-02, 9.0070e-01],
        [6.8563e-01, 3.1437e-01],
        [6.8378e-01, 3.1622e-01],
        [1.6211e-03, 9.9838e-01],
        [2.1016e-03, 9.9790e-01],
        [9.8439e-04, 9.9902e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


19it [00:01, 11.38it/s]

tensor([[9.1292e-04, 9.9909e-01],
        [6.5002e-03, 9.9350e-01],
        [3.5623e-02, 9.6438e-01],
        [4.2966e-02, 9.5703e-01],
        [1.6951e-01, 8.3049e-01],
        [2.4096e-01, 7.5904e-01],
        [3.5255e-01, 6.4745e-01],
        [9.1326e-01, 8.6745e-02]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9341, 0.0659],
        [0.5343, 0.4657],
        [0.3789, 0.6211],
        [0.0088, 0.9912],
        [0.0133, 0.9867],
        [0.0339, 0.9661],
        [0.0132, 0.9868],
        [0.0209, 0.9791]], device='cuda:0')
tensor([1, 0, 0, 1, 1, 1, 1, 1])
tensor([[5.9695e-03, 9.9403e-01],
        [2.3861e-02, 9.7614e-01],
        [1.8282e-03, 9.9817e-01],
        [3.0621e-03, 9.9694e-01],
        [4.2181e-01, 5.7819e-01],
        [7.6289e-01, 2.3711e-01],
        [9.5998e-04, 9.9904e-01],
        [2.2489e-04, 9.9978e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


23it [00:02, 12.06it/s]

tensor([[1.2855e-03, 9.9871e-01],
        [1.7586e-03, 9.9824e-01],
        [6.9432e-04, 9.9931e-01],
        [8.6003e-01, 1.3997e-01],
        [1.1541e-02, 9.8846e-01],
        [6.5255e-03, 9.9347e-01],
        [1.4038e-02, 9.8596e-01],
        [2.7411e-03, 9.9726e-01]], device='cuda:0')
tensor([1, 1, 1, 0, 1, 1, 1, 1])
tensor([[1.3681e-04, 9.9986e-01],
        [1.9389e-04, 9.9981e-01],
        [3.9228e-01, 6.0772e-01],
        [1.8043e-01, 8.1957e-01],
        [2.6875e-01, 7.3125e-01],
        [9.6387e-02, 9.0361e-01],
        [1.9597e-01, 8.0403e-01],
        [1.8840e-01, 8.1160e-01]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.3959, 0.6041],
        [0.1089, 0.8911],
        [0.1671, 0.8329],
        [0.0026, 0.9974],
        [0.0339, 0.9661],
        [0.0964, 0.9036],
        [0.2373, 0.7627],
        [0.2663, 0.7337]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


25it [00:02, 12.36it/s]

tensor([[0.1583, 0.8417],
        [0.4837, 0.5163],
        [0.0778, 0.9222],
        [0.0972, 0.9028],
        [0.0280, 0.9720],
        [0.0253, 0.9747],
        [0.0041, 0.9959],
        [0.0470, 0.9530]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.1436, 0.8564],
        [0.7327, 0.2673],
        [0.7931, 0.2069],
        [0.6385, 0.3615],
        [0.0503, 0.9497],
        [0.0826, 0.9174],
        [0.7344, 0.2656],
        [0.7282, 0.2718]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.6927, 0.3073],
        [0.7250, 0.2750],
        [0.6931, 0.3069],
        [0.6563, 0.3437],
        [0.6546, 0.3454],
        [0.7162, 0.2838],
        [0.7717, 0.2283],
        [0.7881, 0.2119]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


29it [00:02, 11.57it/s]

tensor([[0.8127, 0.1873],
        [0.0194, 0.9806],
        [0.0227, 0.9773],
        [0.0208, 0.9792],
        [0.0101, 0.9899],
        [0.0101, 0.9899],
        [0.0169, 0.9831],
        [0.0067, 0.9933]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0096, 0.9904],
        [0.0063, 0.9937],
        [0.0091, 0.9909],
        [0.0051, 0.9949],
        [0.0032, 0.9968],
        [0.0249, 0.9751],
        [0.0287, 0.9713],
        [0.0040, 0.9960]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0035, 0.9965],
        [0.0050, 0.9950],
        [0.0161, 0.9839],
        [0.0411, 0.9589],
        [0.0242, 0.9758],
        [0.0250, 0.9750],
        [0.0109, 0.9891],
        [0.8521, 0.1479]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


31it [00:03, 11.54it/s]

tensor([[0.9358, 0.0642],
        [0.9043, 0.0957],
        [0.6987, 0.3013],
        [0.6769, 0.3231],
        [0.9015, 0.0985],
        [0.7052, 0.2948],
        [0.7973, 0.2027],
        [0.7438, 0.2562]], device='cuda:0')
tensor([1, 1, 1, 1, 0, 0, 0, 0])
tensor([[0.8059, 0.1941],
        [0.6515, 0.3485],
        [0.8385, 0.1615],
        [0.8650, 0.1350],
        [0.8947, 0.1053],
        [0.8119, 0.1881],
        [0.8114, 0.1886],
        [0.8575, 0.1425]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9030, 0.0970],
        [0.8183, 0.1817],
        [0.8968, 0.1032],
        [0.8860, 0.1140],
        [0.7906, 0.2094],
        [0.8249, 0.1751],
        [0.8484, 0.1516],
        [0.7935, 0.2065]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


35it [00:03, 11.66it/s]

tensor([[0.8903, 0.1097],
        [0.8765, 0.1235],
        [0.8289, 0.1711],
        [0.6659, 0.3341],
        [0.8264, 0.1736],
        [0.8441, 0.1559],
        [0.8361, 0.1639],
        [0.6710, 0.3290]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8055, 0.1945],
        [0.8157, 0.1843],
        [0.8276, 0.1724],
        [0.8528, 0.1472],
        [0.5494, 0.4506],
        [0.8723, 0.1277],
        [0.8672, 0.1328],
        [0.7980, 0.2020]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7710, 0.2290],
        [0.8900, 0.1100],
        [0.6023, 0.3977],
        [0.7186, 0.2814],
        [0.9090, 0.0910],
        [0.8263, 0.1737],
        [0.8878, 0.1122],
        [0.5039, 0.4961]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


37it [00:03, 11.69it/s]

tensor([[0.7770, 0.2230],
        [0.5245, 0.4755],
        [0.7866, 0.2134],
        [0.8724, 0.1276],
        [0.9132, 0.0868],
        [0.8364, 0.1636],
        [0.8332, 0.1668],
        [0.5975, 0.4025]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7495, 0.2505],
        [0.7222, 0.2778],
        [0.8279, 0.1721],
        [0.7295, 0.2705],
        [0.8773, 0.1227],
        [0.8281, 0.1719],
        [0.9267, 0.0733],
        [0.9145, 0.0855]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9150, 0.0850],
        [0.7368, 0.2632],
        [0.7778, 0.2222],
        [0.8676, 0.1324],
        [0.7808, 0.2192],
        [0.8150, 0.1850],
        [0.0659, 0.9341],
        [0.0459, 0.9541]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


41it [00:03, 11.94it/s]

tensor([[0.9188, 0.0812],
        [0.7545, 0.2455],
        [0.9308, 0.0692],
        [0.3587, 0.6413],
        [0.8085, 0.1915],
        [0.6395, 0.3605],
        [0.7639, 0.2361],
        [0.7296, 0.2704]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7812, 0.2188],
        [0.0378, 0.9622],
        [0.1063, 0.8937],
        [0.8897, 0.1103],
        [0.5269, 0.4731],
        [0.8899, 0.1101],
        [0.9085, 0.0915],
        [0.8633, 0.1367]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8922, 0.1078],
        [0.7267, 0.2733],
        [0.7933, 0.2067],
        [0.7750, 0.2250],
        [0.6658, 0.3342],
        [0.8438, 0.1562],
        [0.8730, 0.1270],
        [0.8849, 0.1151]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


43it [00:04, 11.97it/s]

tensor([[0.8906, 0.1094],
        [0.4991, 0.5009],
        [0.4570, 0.5430],
        [0.2693, 0.7307],
        [0.1417, 0.8583],
        [0.1444, 0.8556],
        [0.7462, 0.2538],
        [0.6407, 0.3593]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8020, 0.1980],
        [0.7922, 0.2078],
        [0.6584, 0.3416],
        [0.7261, 0.2739],
        [0.7875, 0.2125],
        [0.8088, 0.1912],
        [0.8898, 0.1102],
        [0.1417, 0.8583]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.2066, 0.7934],
        [0.1021, 0.8979],
        [0.8411, 0.1589],
        [0.8344, 0.1656],
        [0.8726, 0.1274],
        [0.7841, 0.2159],
        [0.8769, 0.1231],
        [0.7534, 0.2466]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


45it [00:04, 11.29it/s]

tensor([[0.8644, 0.1356],
        [0.6776, 0.3224],
        [0.8658, 0.1342],
        [0.7925, 0.2075],
        [0.8045, 0.1955],
        [0.7864, 0.2136],
        [0.8308, 0.1692],
        [0.8992, 0.1008]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6951, 0.3049],
        [0.7823, 0.2177],
        [0.7693, 0.2307],
        [0.6082, 0.3918],
        [0.6993, 0.3007],
        [0.8551, 0.1449],
        [0.8131, 0.1869],
        [0.8297, 0.1703]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


49it [00:04, 12.18it/s]

tensor([[0.7898, 0.2102],
        [0.7967, 0.2033],
        [0.7567, 0.2433],
        [0.8269, 0.1731],
        [0.8231, 0.1769],
        [0.7228, 0.2772],
        [0.6716, 0.3284],
        [0.7679, 0.2321]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6461, 0.3539],
        [0.7786, 0.2214],
        [0.6937, 0.3063],
        [0.7193, 0.2807],
        [0.8568, 0.1432],
        [0.8578, 0.1422],
        [0.1708, 0.8292],
        [0.1715, 0.8285]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8298, 0.1702],
        [0.7840, 0.2160],
        [0.7555, 0.2445],
        [0.7713, 0.2287],
        [0.6712, 0.3288],
        [0.8200, 0.1800],
        [0.7392, 0.2608],
        [0.8193, 0.1807]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


51it [00:04, 11.55it/s]

tensor([[0.9044, 0.0956],
        [0.8775, 0.1225],
        [0.8808, 0.1192],
        [0.6885, 0.3115],
        [0.7390, 0.2610],
        [0.8516, 0.1484],
        [0.8620, 0.1380],
        [0.6451, 0.3549]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6463, 0.3537],
        [0.7007, 0.2993],
        [0.5299, 0.4701],
        [0.4860, 0.5140],
        [0.5204, 0.4796],
        [0.5494, 0.4506],
        [0.6164, 0.3836],
        [0.8192, 0.1808]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8409, 0.1591],
        [0.7586, 0.2414],
        [0.8059, 0.1941],
        [0.9154, 0.0846],
        [0.8966, 0.1034],
        [0.8275, 0.1725],
        [0.6781, 0.3219],
        [0.8273, 0.1727]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


55it [00:04, 12.75it/s]

tensor([[0.8066, 0.1934],
        [0.8759, 0.1241],
        [0.6074, 0.3926],
        [0.8722, 0.1278],
        [0.8666, 0.1334],
        [0.8544, 0.1456],
        [0.7636, 0.2364],
        [0.9184, 0.0816]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9255, 0.0745],
        [0.8365, 0.1635],
        [0.9121, 0.0879],
        [0.7164, 0.2836],
        [0.2637, 0.7363],
        [0.3811, 0.6189],
        [0.7331, 0.2669],
        [0.8754, 0.1246]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9055, 0.0945],
        [0.7933, 0.2067],
        [0.8381, 0.1619],
        [0.7225, 0.2775],
        [0.7415, 0.2585],
        [0.7302, 0.2698],
        [0.7925, 0.2075],
        [0.8154, 0.1846]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


59it [00:05, 14.50it/s]

tensor([[0.8601, 0.1399],
        [0.8274, 0.1726],
        [0.6498, 0.3502],
        [0.0651, 0.9349],
        [0.7722, 0.2278],
        [0.6457, 0.3543],
        [0.8891, 0.1109],
        [0.8615, 0.1385]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9013, 0.0987],
        [0.8586, 0.1414],
        [0.8981, 0.1019],
        [0.7721, 0.2279],
        [0.7650, 0.2350],
        [0.7405, 0.2595],
        [0.5394, 0.4606],
        [0.4866, 0.5134]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6456, 0.3544],
        [0.4910, 0.5090],
        [0.6949, 0.3051],
        [0.6698, 0.3302],
        [0.7593, 0.2407],
        [0.9463, 0.0537],
        [0.8570, 0.1430],
        [0.9348, 0.0652]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([0.9122, 0.0878], device='cuda:0')
tensor([0])
Error : number of targets and predicted outputs do not match


59it [00:05, 11.02it/s]

val_accuracy:  82.75862068965517
epoch:3,lr:0.0001,loss:0.412689208984375,train_cm:[[2757  168]
 [ 776 1230]],val_cm:[[212  22]
 [ 58 172]],train_acc:80.85581018049078, val_acc:82.75862068965517



617it [02:43,  3.78it/s]
2it [00:00,  2.77it/s]

tensor([[0.0201, 0.9799],
        [0.0159, 0.9841],
        [0.0356, 0.9644],
        [0.0185, 0.9815],
        [0.0283, 0.9717],
        [0.0444, 0.9556],
        [0.2477, 0.7523],
        [0.0150, 0.9850]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9611, 0.0389],
        [0.9376, 0.0624],
        [0.9527, 0.0473],
        [0.9518, 0.0482],
        [0.6493, 0.3507],
        [0.8195, 0.1805],
        [0.6223, 0.3777],
        [0.2721, 0.7279]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


4it [00:00,  3.56it/s]

tensor([[0.0104, 0.9896],
        [0.0932, 0.9068],
        [0.0579, 0.9421],
        [0.0057, 0.9943],
        [0.8314, 0.1686],
        [0.9330, 0.0670],
        [0.0111, 0.9889],
        [0.0216, 0.9784]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0388, 0.9612],
        [0.0173, 0.9827],
        [0.0284, 0.9716],
        [0.9655, 0.0345],
        [0.9129, 0.0871],
        [0.1575, 0.8425],
        [0.2353, 0.7647],
        [0.8059, 0.1941]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


7it [00:01,  5.42it/s]

tensor([[2.5579e-04, 9.9974e-01],
        [2.2574e-04, 9.9977e-01],
        [1.7402e-03, 9.9826e-01],
        [8.2730e-04, 9.9917e-01],
        [2.0103e-02, 9.7990e-01],
        [9.7342e-01, 2.6581e-02],
        [9.6475e-01, 3.5245e-02],
        [9.4999e-01, 5.0006e-02]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9495, 0.0505],
        [0.7537, 0.2463],
        [0.9844, 0.0156],
        [0.9574, 0.0426],
        [0.1164, 0.8836],
        [0.8527, 0.1473],
        [0.0052, 0.9948],
        [0.0142, 0.9858]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0275, 0.9725],
        [0.0124, 0.9876],
        [0.0058, 0.9942],
        [0.0040, 0.9960],
        [0.0099, 0.9901],
        [0.0181, 0.9819],
        [0.2935, 0.7065],
        [0.2714, 0.7286]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


9it [00:01,  6.53it/s]

tensor([[0.0332, 0.9668],
        [0.0692, 0.9308],
        [0.7352, 0.2648],
        [0.7985, 0.2015],
        [0.9269, 0.0731],
        [0.8137, 0.1863],
        [0.9179, 0.0821],
        [0.0188, 0.9812]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0024, 0.9976],
        [0.0963, 0.9037],
        [0.1052, 0.8948],
        [0.0448, 0.9552],
        [0.4299, 0.5701],
        [0.1513, 0.8487],
        [0.1626, 0.8374],
        [0.0059, 0.9941]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0166, 0.9834],
        [0.0430, 0.9570],
        [0.0516, 0.9484],
        [0.0334, 0.9666],
        [0.0406, 0.9594],
        [0.0253, 0.9747],
        [0.0404, 0.9596],
        [0.0325, 0.9675]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


13it [00:01,  8.70it/s]

tensor([[0.0148, 0.9852],
        [0.0070, 0.9930],
        [0.0582, 0.9418],
        [0.1013, 0.8987],
        [0.2309, 0.7691],
        [0.0044, 0.9956],
        [0.0332, 0.9668],
        [0.0031, 0.9969]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0028, 0.9972],
        [0.0374, 0.9626],
        [0.0688, 0.9312],
        [0.0275, 0.9725],
        [0.0741, 0.9259],
        [0.0255, 0.9745],
        [0.0190, 0.9810],
        [0.0290, 0.9710]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0343, 0.9657],
        [0.9870, 0.0130],
        [0.9793, 0.0207],
        [0.9861, 0.0139],
        [0.7135, 0.2865],
        [0.7911, 0.2089],
        [0.0136, 0.9864],
        [0.0570, 0.9430]], device='cuda:0')
tensor([1, 0, 0, 0, 1, 1, 1, 1])


15it [00:01,  9.44it/s]

tensor([[0.4211, 0.5789],
        [0.8644, 0.1356],
        [0.9369, 0.0631],
        [0.9088, 0.0912],
        [0.4965, 0.5035],
        [0.8819, 0.1181],
        [0.7427, 0.2573],
        [0.0215, 0.9785]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0318, 0.9682],
        [0.0194, 0.9806],
        [0.7585, 0.2415],
        [0.0213, 0.9787],
        [0.1197, 0.8803],
        [0.0721, 0.9279],
        [0.0584, 0.9416],
        [0.0228, 0.9772]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0327, 0.9673],
        [0.0317, 0.9683],
        [0.0508, 0.9492],
        [0.8965, 0.1035],
        [0.8363, 0.1637],
        [0.9584, 0.0416],
        [0.8865, 0.1135],
        [0.7559, 0.2441]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


19it [00:02, 10.78it/s]

tensor([[0.1903, 0.8097],
        [0.3976, 0.6024],
        [0.8563, 0.1437],
        [0.9608, 0.0392],
        [0.8447, 0.1553],
        [0.0068, 0.9932],
        [0.0052, 0.9948],
        [0.0108, 0.9892]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0090, 0.9910],
        [0.0132, 0.9868],
        [0.0290, 0.9710],
        [0.0179, 0.9821],
        [0.1147, 0.8853],
        [0.1838, 0.8162],
        [0.2339, 0.7661],
        [0.9772, 0.0228]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9847, 0.0153],
        [0.9509, 0.0491],
        [0.9439, 0.0561],
        [0.0271, 0.9729],
        [0.0339, 0.9661],
        [0.0425, 0.9575],
        [0.0584, 0.9416],
        [0.0597, 0.9403]], device='cuda:0')
tensor([1, 0, 0, 1, 1, 1, 1, 1])


21it [00:02, 11.36it/s]

tensor([[0.0051, 0.9949],
        [0.0418, 0.9582],
        [0.0162, 0.9838],
        [0.0530, 0.9470],
        [0.5511, 0.4489],
        [0.8320, 0.1680],
        [0.0041, 0.9959],
        [0.0041, 0.9959]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0030, 0.9970],
        [0.0065, 0.9935],
        [0.0063, 0.9937],
        [0.9647, 0.0353],
        [0.0267, 0.9733],
        [0.0253, 0.9747],
        [0.1094, 0.8906],
        [0.0182, 0.9818]], device='cuda:0')
tensor([1, 1, 1, 0, 1, 1, 1, 1])


23it [00:02, 10.95it/s]

tensor([[0.0011, 0.9989],
        [0.0013, 0.9987],
        [0.3281, 0.6719],
        [0.2883, 0.7117],
        [0.2477, 0.7523],
        [0.0858, 0.9142],
        [0.1211, 0.8789],
        [0.1405, 0.8595]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.3695, 0.6305],
        [0.1105, 0.8895],
        [0.0501, 0.9499],
        [0.0045, 0.9955],
        [0.0109, 0.9891],
        [0.2996, 0.7004],
        [0.2648, 0.7352],
        [0.5980, 0.4020]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.1322, 0.8678],
        [0.2907, 0.7093],
        [0.2032, 0.7968],
        [0.3225, 0.6775],
        [0.0631, 0.9369],
        [0.0621, 0.9379],
        [0.0370, 0.9630],
        [0.1174, 0.8826]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


27it [00:02, 11.33it/s]

tensor([[0.0511, 0.9489],
        [0.8309, 0.1691],
        [0.8269, 0.1731],
        [0.8076, 0.1924],
        [0.2271, 0.7729],
        [0.6755, 0.3245],
        [0.8743, 0.1257],
        [0.9307, 0.0693]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.8492, 0.1508],
        [0.7987, 0.2013],
        [0.6119, 0.3881],
        [0.9238, 0.0762],
        [0.8551, 0.1449],
        [0.9431, 0.0569],
        [0.8670, 0.1330],
        [0.9568, 0.0432]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9244, 0.0756],
        [0.1811, 0.8189],
        [0.2539, 0.7461],
        [0.2911, 0.7089],
        [0.0361, 0.9639],
        [0.0423, 0.9577],
        [0.0720, 0.9280],
        [0.0157, 0.9843]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])


29it [00:02, 10.89it/s]

tensor([[0.0409, 0.9591],
        [0.0209, 0.9791],
        [0.0394, 0.9606],
        [0.0195, 0.9805],
        [0.0206, 0.9794],
        [0.0437, 0.9563],
        [0.0912, 0.9088],
        [0.0133, 0.9867]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.0173, 0.9827],
        [0.0354, 0.9646],
        [0.0365, 0.9635],
        [0.0747, 0.9253],
        [0.0739, 0.9261],
        [0.0349, 0.9651],
        [0.0309, 0.9691],
        [0.9783, 0.0217]], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1])
tensor([[0.9915, 0.0085],
        [0.9879, 0.0121],
        [0.7188, 0.2812],
        [0.6488, 0.3512],
        [0.9387, 0.0613],
        [0.8308, 0.1692],
        [0.4108, 0.5892],
        [0.4103, 0.5897]], device='cuda:0')
tensor([1, 1, 1, 1, 0, 0, 0, 0])


33it [00:03, 11.31it/s]

tensor([[0.9779, 0.0221],
        [0.9682, 0.0318],
        [0.9801, 0.0199],
        [0.9855, 0.0145],
        [0.9940, 0.0060],
        [0.8661, 0.1339],
        [0.9702, 0.0298],
        [0.9736, 0.0264]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9798, 0.0202],
        [0.9811, 0.0189],
        [0.9782, 0.0218],
        [0.9635, 0.0365],
        [0.9570, 0.0430],
        [0.9457, 0.0543],
        [0.9756, 0.0244],
        [0.8726, 0.1274]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9815, 0.0185],
        [0.9671, 0.0329],
        [0.9671, 0.0329],
        [0.9540, 0.0460],
        [0.8973, 0.1027],
        [0.9671, 0.0329],
        [0.9736, 0.0264],
        [0.9508, 0.0492]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


35it [00:03, 11.76it/s]

tensor([[0.9470, 0.0530],
        [0.9595, 0.0405],
        [0.9566, 0.0434],
        [0.9246, 0.0754],
        [0.9177, 0.0823],
        [0.9725, 0.0275],
        [0.9836, 0.0164],
        [0.9795, 0.0205]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9858, 0.0142],
        [0.9813, 0.0187],
        [0.6554, 0.3446],
        [0.8720, 0.1280],
        [0.9886, 0.0114],
        [0.9498, 0.0502],
        [0.9438, 0.0562],
        [0.9703, 0.0297]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7380, 0.2620],
        [0.7125, 0.2875],
        [0.8846, 0.1154],
        [0.9653, 0.0347],
        [0.9722, 0.0278],
        [0.9560, 0.0440],
        [0.7669, 0.2331],
        [0.8310, 0.1690]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


39it [00:03, 11.78it/s]

tensor([[0.8621, 0.1379],
        [0.9844, 0.0156],
        [0.9116, 0.0884],
        [0.9547, 0.0453],
        [0.9672, 0.0328],
        [0.9406, 0.0594],
        [0.9777, 0.0223],
        [0.9707, 0.0293]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9807, 0.0193],
        [0.9541, 0.0459],
        [0.9504, 0.0496],
        [0.9828, 0.0172],
        [0.9679, 0.0321],
        [0.9759, 0.0241],
        [0.0920, 0.9080],
        [0.0891, 0.9109]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9790, 0.0210],
        [0.9684, 0.0316],
        [0.9730, 0.0270],
        [0.8748, 0.1252],
        [0.8615, 0.1385],
        [0.9894, 0.0106],
        [0.9024, 0.0976],
        [0.9389, 0.0611]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


41it [00:03, 11.84it/s]

tensor([[0.8776, 0.1224],
        [0.0788, 0.9212],
        [0.0599, 0.9401],
        [0.8503, 0.1497],
        [0.7370, 0.2630],
        [0.9801, 0.0199],
        [0.9875, 0.0125],
        [0.9700, 0.0300]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9781, 0.0219],
        [0.9445, 0.0555],
        [0.9756, 0.0244],
        [0.9871, 0.0129],
        [0.8741, 0.1259],
        [0.9710, 0.0290],
        [0.9459, 0.0541],
        [0.8925, 0.1075]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9708, 0.0292],
        [0.9575, 0.0425],
        [0.9572, 0.0428],
        [0.8997, 0.1003],
        [0.5363, 0.4637],
        [0.8123, 0.1877],
        [0.7705, 0.2295],
        [0.9152, 0.0848]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


45it [00:04, 12.10it/s]

tensor([[0.8490, 0.1510],
        [0.8873, 0.1127],
        [0.9126, 0.0874],
        [0.9040, 0.0960],
        [0.9652, 0.0348],
        [0.9574, 0.0426],
        [0.9640, 0.0360],
        [0.7097, 0.2903]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.8660, 0.1340],
        [0.8218, 0.1782],
        [0.9743, 0.0257],
        [0.9270, 0.0730],
        [0.9673, 0.0327],
        [0.9476, 0.0524],
        [0.9543, 0.0457],
        [0.9451, 0.0549]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9353, 0.0647],
        [0.9795, 0.0205],
        [0.9039, 0.0961],
        [0.9203, 0.0797],
        [0.9271, 0.0729],
        [0.8620, 0.1380],
        [0.9694, 0.0306],
        [0.9824, 0.0176]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


47it [00:04, 12.09it/s]

tensor([[0.9406, 0.0594],
        [0.9422, 0.0578],
        [0.9517, 0.0483],
        [0.8277, 0.1723],
        [0.9632, 0.0368],
        [0.9833, 0.0167],
        [0.9439, 0.0561],
        [0.9766, 0.0234]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9598, 0.0402],
        [0.9650, 0.0350],
        [0.9078, 0.0922],
        [0.9481, 0.0519],
        [0.9754, 0.0246],
        [0.8787, 0.1213],
        [0.9644, 0.0356],
        [0.8952, 0.1048]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.6615, 0.3385],
        [0.8304, 0.1696],
        [0.7525, 0.2475],
        [0.8657, 0.1343],
        [0.9464, 0.0536],
        [0.9294, 0.0706],
        [0.4523, 0.5477],
        [0.1287, 0.8713]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


51it [00:04, 11.82it/s]

tensor([[0.9203, 0.0797],
        [0.9152, 0.0848],
        [0.9688, 0.0312],
        [0.9575, 0.0425],
        [0.8817, 0.1183],
        [0.9617, 0.0383],
        [0.9077, 0.0923],
        [0.9746, 0.0254]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9795, 0.0205],
        [0.9637, 0.0363],
        [0.9872, 0.0128],
        [0.9549, 0.0451],
        [0.9448, 0.0552],
        [0.9570, 0.0430],
        [0.9519, 0.0481],
        [0.9046, 0.0954]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7504, 0.2496],
        [0.8977, 0.1023],
        [0.8651, 0.1349],
        [0.6907, 0.3093],
        [0.5791, 0.4209],
        [0.8572, 0.1428],
        [0.9463, 0.0537],
        [0.9494, 0.0506]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


53it [00:04, 12.39it/s]

tensor([[0.9629, 0.0371],
        [0.9632, 0.0368],
        [0.9802, 0.0198],
        [0.9777, 0.0223],
        [0.8885, 0.1115],
        [0.8838, 0.1162],
        [0.9496, 0.0504],
        [0.9047, 0.0953]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.7873, 0.2127],
        [0.9545, 0.0455],
        [0.7141, 0.2859],
        [0.9581, 0.0419],
        [0.9675, 0.0325],
        [0.9625, 0.0375],
        [0.9600, 0.0400],
        [0.9687, 0.0313]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9333, 0.0667],
        [0.7587, 0.2413],
        [0.9591, 0.0409],
        [0.9355, 0.0645],
        [0.6979, 0.3021],
        [0.9219, 0.0781],
        [0.9684, 0.0316],
        [0.9611, 0.0389]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


57it [00:05, 13.23it/s]

tensor([[0.9483, 0.0517],
        [0.8370, 0.1630],
        [0.9321, 0.0679],
        [0.8497, 0.1503],
        [0.8708, 0.1292],
        [0.9458, 0.0542],
        [0.9319, 0.0681],
        [0.9589, 0.0411]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9271, 0.0729],
        [0.9251, 0.0749],
        [0.6588, 0.3412],
        [0.3274, 0.6726],
        [0.8770, 0.1230],
        [0.7528, 0.2472],
        [0.9722, 0.0278],
        [0.9743, 0.0257]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([[0.9784, 0.0216],
        [0.9767, 0.0233],
        [0.9616, 0.0384],
        [0.9307, 0.0693],
        [0.9457, 0.0543],
        [0.9118, 0.0882],
        [0.8628, 0.1372],
        [0.4572, 0.5428]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])


59it [00:05, 11.00it/s]

tensor([[0.8499, 0.1501],
        [0.9774, 0.0226],
        [0.9510, 0.0490],
        [0.9426, 0.0574],
        [0.9513, 0.0487],
        [0.9519, 0.0481],
        [0.8678, 0.1322],
        [0.9710, 0.0290]], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0])
tensor([0.9408, 0.0592], device='cuda:0')
tensor([0])
Error : number of targets and predicted outputs do not match
val_accuracy:  83.62068965517241
epoch:4,lr:0.0001,loss:0.3988724648952484,train_cm:[[2761  164]
 [ 762 1244]],val_cm:[[224  10]
 [ 66 164]],train_acc:81.22084769823566, val_acc:83.62068965517241



226it [01:00,  3.78it/s]